services:
  ft_transcendence:
    container_name: transcendence
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./ft_transcendence:/ft_transcendence
      #- ./data/web/static:/data/web/static/
      #- ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql_transcendence
    networks:
      - transcendence

  psql_transcendence:
    container_name: psql
    image: postgres:16.4-alpine3.20
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
    networks:
      - transcendence
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./dotenv_files/.env
    networks:
      - transcendence

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    user: "$UID:$GID"
    networks:
      - transcendence

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  psql_data:
  grafana_data:
  prometheus_data: