FROM prom/prometheus:latest

# Modifica permissões do diretório montado antes de iniciar o Prometheus
USER root
RUN mkdir -p /prometheus/data && chown -R nobody /prometheus/data

# Defina o usuário padrão para execução do Prometheus
USER nobody

CMD [ "--config.file=/etc/prometheus/prometheus.yml", "--web.enable-lifecycle" ]
