services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8001:8001
    volumes:
      - app_vol:/ft_transcendence
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db
    networks:
      - net

  db:
    container_name: db
    image: postgres:16.4-alpine3.20
    volumes:
      - db_vol:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    networks:
      - net
    ports:
      - 5432:5432

  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./dotenv_files/.env
    networks:
      - net

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_vol:/var/lib/grafana
    env_file:
      - ./dotenv_files/.env
    networks:
      - net

  promet:
    container_name: promet
    image: prom/prometheus
    volumes:
      - promet_vol:/etc/prometheus
    ports:
      - 9090:9090
    networks:
      - net

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - net
    depends_on:
      - app

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - 9001:9001
      - 9002:9002
    env_file:
      - ./dotenv_files/.env
    volumes:
      - minio_vol:/data
    networks:
      - net
    command: server /data --console-address ":9002"

networks:
  net:
    driver: bridge

volumes:
  app_vol:
  db_vol:
  grafana_vol:
  promet_vol:
  minio_vol:
