global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["ft_transcendence:8000"]
    relabel_configs:
      - source_labels:
        regex: "([^:]+):\\d+"
        target_label: "instance"