receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    send_batch_size: 512

exporters:
  debug: {}  # Exporter de debug para verificação
  otlp:
    endpoint: "collector:4318"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9091"  # Endpoint para o Prometheus coletar métricas

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
  pprof: {}
  zpages: {}

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]  # Exporter para Prometheus
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
