---
filebeat.inputs:
  - type: filestream
    id: default-filestream
    paths:
      - ingest_data/*.log
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
processors:
- add_docker_metadata:
    docker_fields: ["container.id", "container.name", "image.name"]
setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
output.logstash:
  hosts: ["logstash:5044"]