elasticsearch.hosts: ["https://elasticsearch:9200"]

# Aceitar certificados autoassinados
elasticsearch.ssl.verificationMode: none

xpack.reporting.roles.enabled: false

# Ativar SSL para o Kibana
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/kibana.crt
server.ssl.key: /usr/share/kibana/config/certs/kibana.key

# # Chaves de criptografia
# xpack.security.encryptionKey: "uma-chave-unica-e-longa-para-seguranca"
# xpack.reporting.encryptionKey: "uma-chave-unica-e-longa-para-relatorios"
# xpack.encryptedSavedObjects.encryptionKey: "uma-chave-unica-e-longa-para-objetos-salvos"

# Autenticação do Kibana
elasticsearch.username: ${ELASTICSEARCH_USERNAME}
elasticsearch.password: ${ELASTICSEARCH_PASSWORD}

# Certificado da CA
elasticsearch.ssl.certificateAuthorities: "/usr/share/kibana/config/certs/ca/ca.crt"