name: compilation

on:
  pull_request:
    branches:
    - main
    - developer
    - back
    - front
    - devops
jobs:
  build:
    runs-on: debian-latest
    name: compilation
    steps:
    - uses: actions/checkout@v3
    - name: basic_install
      run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y 
    - name: transcendence
      run: make
    # - name: test
    #   run: make tests