name: compilation

on:
  pull_request:
    branches:
      - main
      - developer
      - back
      - front
      - devops

jobs:
  build:
    runs-on: debian-latest
    name: compilation
    steps:
      # Faz checkout do repositório
      - uses: actions/checkout@v3
      
      # Instala o Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Verifica a instalação do Docker
      - name: Verify Docker Installation
        run: |
          docker --version
          docker-compose --version

      # Compila o projeto
      - name: transcendence
        run: make

      # Rodar testes (descomente quando estiver pronto)
      # - name: test
      #   run: make tests
