name: tests

on:
  pull_request:
    branches:
    - develop
    - main
jobs:
  build:
    runs-on: debian-latest
    name: tests
    steps:
    - uses: actions/checkout@v3
    - name: basic_install
      run: sudo apt-get update && sudo apt upgrade && sudo apt-get install -y 
    - name: tests
      run: make tests